name: SentinelOps CI/CD

on:
  push:
    branches: [ main, CI/CD ] # Trigger on both branches
  pull_request:
    branches: [ main ]
  workflow_dispatch: # This adds a manual "Run" button in the Actions tab

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install PyYAML flake8

      - name: Lint Code
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Build Docker Image
        run: docker build -t techops-monitoring:test .

      - name: Validate Kubernetes Manifests
        run: |
          python3 -c "import yaml; list(yaml.safe_load_all(open('kubernetes.yaml')))"
          echo "Kubernetes YAML is syntactically valid."